/** Declaration file generated by dts-gen */

export class AmeComponent {
    constructor(_config: any, _contract: any);

    decodeResponseData(_methodResponseType: any, _resDataEncode: any): any;

    encodeRequestParams(_methodRequestParamsType: any, _requestParamValue: any): any;

    getComponentMethods(_x8: any, ...args: any[]): any;

    getComponentOptions(...args: any[]): any;

    getMethodInstruction(_x10: any, ...args: any[]): any;

    getMethodReqAndRes(_x9: any, ...args: any[]): any;

    sendGetRequest(_x: any, _x2: any, ...args: any[]): any;

    sendPostAndPutRequest(_x3: any, _x4: any, _x5: any, _x6: any, _x7: any, ...args: any[]): any;

}

